### ISSUE TITLE
Secrets added for cloud enablement causing Kubernetes fail to deploy application

### ISSUE THREAD

**Issue by johnmcollier** [ibm-developer/generator-ibm-cloud-enablement#275]
When node projects are generated with the "Alert" template for IBM Cloud enablement, this section is added to the deployment.yaml

```
env:
          - name: service_alert_notification
            valueFrom:
              secretKeyRef:
                name: binding-alert-name
                key: binding
```

If the Kubernetes cluster doesn't have the binding-alert-name secret, it'll fail to deploy. Is this secret needed? If not, can it be taken out? If it is needed, how can we work around it?
